version: "3.9"
services:
  reportgen-nodejs:
    build: ./notes-app
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: always
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=deepak
      - MONGO_HOST=mobmon-mongodb
      - MONGO_PORT=27017
      - API_PORT=8081
      - TOKEN_KEY=fjalfjdkhgj3hr43
    volumes:
      - ./data:/opt/deepak/app/data
      - ./certs:/etc/letsencrypt/live/
  mobmon-mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=deepak
